# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks

target 'DYZB' do
  use_frameworks!

  # Pods for DYZB
	pod 'Alamofire'
end
